[package]
name = "brim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
muncher = "0.7.0"
reedline = "0.28.0"
